[package]
name = "armouryd"
edition.workspace = true
version.workspace = true
license.workspace = true

[dependencies]
anyhow.workspace = true
async-trait.workspace = true
armoury-proto.workspace = true
serde.workspace = true
serde_json.workspace = true
tokio.workspace = true
toml = "1"
zbus.workspace = true
nvml-wrapper = "0.13"
evdev = { version = "0.13", features = ["tokio"] }
i2cdev = "0.6"
rustfft = "6"
nix = { workspace = true, features = ["ioctl"] }

[dev-dependencies]
tempfile.workspace = true
tokio = { workspace = true, features = ["test-util"] }
